#!/bin/bash

set -ex

apt-get install -y \
    asciidoc \
    asciidoc-base \
    asciidoc-common \
    autoconf \
    automake \
    autopoint \
    autotools-dev \
    debhelper \
    debugedit \
    default-jdk-headless \
    default-jre-headless \
    dh-autoreconf \
    dh-strip-nondeterminism \
    docbook-dsssl \
    docbook-utils \
    docutils-common \
    dwz \
    fig2dev \
    gawk \
    gettext \
    intltool-debian \
    libarchive-zip-perl \
    libaudit-dev \
    libcap-dev \
    libcap-ng-dev \
    libdebhelper-perl \
    libdw-dev \
    libfile-stripnondeterminism-perl \
    libiberty-dev \
    liblzma-dev \
    libnewt-dev \
    libnuma-dev \
    libpci-dev \
    libpng-dev \
    librsvg2-bin \
    libsgmls-perl \
    libslang2-dev \
    libsub-override-perl \
    libtool \
    libudev-dev \
    libunwind-dev \
    lynx \
    lynx-common \
    makedumpfile \
    openjdk-11-jdk-headless \
    openjdk-11-jre-headless \
    opensp \
    pahole \
    po-debconf \
    python-babel-localedata \
    python3-alabaster \
    python3-babel \
    python3-certifi \
    python3-docutils \
    python3-idna \
    python3-imagesize \
    python3-jinja2 \
    python3-markupsafe \
    python3-packaging \
    python3-requests \
    python3-roman \
    python3-snowballstemmer \
    python3-sphinx \
    python3-sphinx-rtd-theme \
    python3-tz \
    python3-urllib3 \
    sgmlspl \
    sharutils \
    sphinx-common \
    sphinx-rtd-theme-common \
    uuid-dev \
    xmlto \
    xsltproc
